# Generated by Django 3.2.8 on 2021-11-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='primary_number',
            field=models.BooleanField(default=False),
        ),
    ]
