# Generated by Django 3.2.8 on 2021-11-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_number_primary_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='primary_number',
        ),
    ]
