# Generated by Django 3.2.8 on 2021-11-01 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_number_primary_number'),
        ('authenticateUser', '0002_auto_20211101_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primay_number', to='subscription.number'),
        ),
    ]
