# Generated by Django 3.2.8 on 2021-11-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_usersubscription'),
        ('authenticateUser', '0003_user_primary_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subs_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
