# Generated by Django 3.2.8 on 2021-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticateUser', '0004_auto_20211101_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_end',
        ),
    ]
